#+title: Emacs config
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el
#+startup: content

* Table of Contents :TOC:
- [[#notes-to-self][Notes to self]]
  - [[#general-useful-keybinds][General Useful Keybinds]]
  - [[#configuration-notes][Configuration notes]]
  - [[#questions][Questions]]
  - [[#configuring-emacs-wo-evil-the-vanilla-way][Configuring Emacs w/o Evil, the Vanilla way]]
  - [[#package-research][Package research]]
- [[#startup-performance][Startup performance]]
- [[#package-management][Package management]]
- [[#prevent-littering][Prevent littering]]
- [[#identify-operating-system][Identify Operating system]]
- [[#basic-ui][Basic UI]]
  - [[#disable-bell][disable bell]]
  - [[#line-numbers][line numbers]]
  - [[#fonts][fonts]]
  - [[#improved-scrolling][improved scrolling]]
  - [[#transparency][transparency]]
  - [[#shorten-y-n-prompt][shorten y-n prompt]]
- [[#basic-functionality][Basic functionality]]
  - [[#all-the-icons][all-the-icons]]
  - [[#nerd-fonts][nerd-fonts]]
  - [[#auto-update-packages][auto-update packages]]
  - [[#add-lisp-functions-dir-to-path][add lisp functions dir to path]]
- [[#keybindings][Keybindings]]
  - [[#make-escape-quit][make escape quit]]
  - [[#meow][meow]]
  - [[#god-mode][god-mode]]
  - [[#evil-mode][evil-mode]]
  - [[#evil-undo-system-undo-treefu][evil-undo-system (undo-tree/fu)]]
  - [[#generalel][general.el]]
  - [[#generalel-generic-binds][general.el generic binds]]
  - [[#hydra][hydra]]
  - [[#crux][crux]]
  - [[#expand-region][expand region]]
  - [[#avy][avy]]
  - [[#free-keys][free-keys]]
  - [[#window-management][window management]]
  - [[#buffer-management][buffer management]]
- [[#ui-configuration][UI Configuration]]
  - [[#ivy--counsel][ivy + counsel]]
  - [[#doom-themes][(doom-)themes]]
  - [[#doom-modeline][doom-modeline]]
  - [[#mini-modeline][mini-modeline]]
  - [[#rainbow-delimiters][rainbow-delimiters]]
  - [[#modus-themes][modus-themes]]
  - [[#which-key][which-key]]
  - [[#helpful][helpful]]
- [[#org][Org]]
  - [[#org-fonts][Org-fonts]]
  - [[#org--agenda][Org + agenda]]
  - [[#bullets][Bullets]]
  - [[#side-padding][side-padding]]
  - [[#org-babel][Org-babel]]
  - [[#toc][TOC]]
- [[#development][Development]]
  - [[#lsp-mode][lsp-mode]]
  - [[#languages][languages]]
  - [[#company-mode][Company mode]]
  - [[#flycheck][Flycheck]]
  - [[#projectile][Projectile]]
  - [[#magit][Magit]]
  - [[#auto-indentation][auto-indentation]]
  - [[#commenting][commenting]]
- [[#terminal][Terminal]]
  - [[#term-mode][term-mode]]
  - [[#vterm][vterm]]
  - [[#shell-mode][shell-mode]]
  - [[#shell-pop-pop-up][shell-pop (pop-up)]]
  - [[#eat][eat]]
  - [[#eshell][Eshell]]
- [[#files][Files]]
  - [[#dired][Dired]]
  - [[#dirvish][dirvish]]
  - [[#sudo-edit][sudo-edit]]
- [[#programs][Programs]]
  - [[#elfeed][elfeed]]
  - [[#eww][eww]]
  - [[#gnus][gnus]]
  - [[#ement][ement]]
  - [[#emacs-jabber][emacs-jabber]]
  - [[#erc][erc]]
  - [[#mastodonel][mastodon.el]]
- [[#applications][Applications]]
  - [[#xmodmap][Xmodmap]]
  - [[#mpv][mpv]]
  - [[#zshrc][zshrc]]
  - [[#firejail][Firejail]]
- [[#special][Special]]
- [[#dvorak-swap-x-and-u][DVORAK swap x and u]]
- [[#runtime-performance][Runtime performance]]

* Notes to self

Emacs Config

Notes:

** General Useful Keybinds

+ C-x C-e to eval at point
+ M-: to eval variable
+ M-o in list for options
+ C-w window management
+ evil C-o to go back to prev location!
+ check-parens to check for errors
+ emacs-lisp-mode-map for viewing local keybinds
+ org-lint to debug
+ C-c C-<SPC> to jump to previous location
+ M-r to center cursor

** Configuration notes

Reduce Emacs startup time:
- :hook
- :bind
- :commands
- :mode
- :after
- :defer

Reset local keybindings:
(setq dired-mode-map (make-keymap))

Unbind key:
(define-key reftex-mode-map (kbd "C-t") nil)

** Questions

:mkdirp, :noweb, toc link
+ :mkdirp yes to create directories when tangling... disabled?
+ How does :noweb work?
+ keybind to search toc for link?

auto-revert-mode, package-initialize
+ auto-revert-mode -- updates file when it changes on disk. use in some modes/files?
+ package-initialize

Look into (meow/god, C-n C-p, ditch evil):
- Meow/God-mode since C-j and C-k (up/down) will be hard in dvorak (could use alt. keys or C-n C-p?)

** Configuring Emacs w/o Evil, the Vanilla way

Emacs keybinds:
https://www.masteringemacs.org/article/mastering-key-bindings-emacs
+ C-h m --- describe-mode
+ M-x describe-keymap

** Package research

List of useful packages:
https://github.com/emacs-tw/awesome-emacs#windows
Good packages to consider:
+ ace-window
  https://github.com/abo-abo/ace-window
+ switch-window
  https://github.com/dimitri/switch-window
+ rcirc
+ discover-my-major
+ discover.el
+ cheatsheet.el
+ speed-type
+ emacs-fireplace
+ edwina (tiling wm)

Poetry and journaling buffer and system...
one general input, then sent over to different categories...
would be nice on android termux too...

A writing org-mode mode?

Ivy-postframe floating minibuffer?

pdf viewer? latex?

gnu guix config?

transfer everything over to .emacs.d?

for having several configs, have testing in dependent .config/ dir, but for more permanent put in .emacs.d so can access all the same settings, history, cache, etc.

custom settings research

keyfreq?

crux to improve everything!

mini-modeline try out?

* Startup performance

#+begin_src emacs-lisp

  ;; The default is 800 kilobytes (measured in bytes)
  (setq gc-cons-threshold (* 50 1000 1000))

  (defun ri/display-startup-time ()
    (message "Emacs loaded in %s with %d garbage collections."
             (format "%.2f seconds"
                     (float-time
                       (time-subtract after-init-time before-init-time)))
             gcs-done))

  (add-hook 'emacs-startup-hook #'ri/display-startup-time)

  (setq native-comp-async-report-warnings-errors 'silent)

#+end_src

* Package management

package management, sources, auto, etc

#+begin_src emacs-lisp

  ;; Package sources ----
  (require 'package) ; package management functions (autoloaded?)
  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))
  (package-initialize) ; initialize package system and prep to be used

  ;; if package-archive-contents is empty (fresh install), ----
  ;;   run package-refresh-contents.
  (unless package-archive-contents
    (package-refresh-contents))

  ;; non-Linux setup use-package ----
  ;; if use-package isn't installed or new update, then package-install it
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  ;; setup use-package ----
  (require 'use-package)
  (setq use-package-always-ensure t) ;; no need to add :ensure t on every package that needs it
                                          ;(setq use-package-always-defer t) ;; explicitly state which to ensure, might break, save first
  (setq use-package-verbose t)

#+end_src

* Prevent littering

#+begin_src emacs-lisp

  ;; Change the user-emacs-directory to keep unwanted things out of ~/.emacs.d
  ;; UNNECESSARY CHANGE, CHANGE BACK!
  (setq user-emacs-directory ;; should be directory of init.el or Emacs.org
        (file-name-directory (or load-file-name (buffer-file-name))))
  (setq user-init-file ;; init.el in user-emacs-directory
        (concat user-emacs-directory "init.el"))
  (setq url-history-file (expand-file-name "url/history" user-emacs-directory))

  ;; no-littering
  (use-package no-littering)

  ;; keep autosaves in emacs dir
  (setq auto-save-file-name-transforms
        `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))

  (setq backup-directory-alist
        `(("." . ,(expand-file-name ".backup/" user-emacs-directory))))

#+end_src

* Identify Operating system

#+begin_src emacs-lisp

  (setq ri/is-guix-system (and (eq system-type 'gnu/linux)
                               (require 'f)
                               (string-equal (f-read "/etc/issue")
                                             "\nThis is the GNU system.  Welcome.\n")))

  (cond ((eq ri/is-guix-system t)
         (load-file (expand-file-name "desktop.el" user-emacs-directory))
         (start-process-shell-command "setxkbmap dv" nil "setxkbmap -layout 'us' -variant 'dvorak' -option ctrl:nocaps")))

#+end_src

* Basic UI

Basic configuration of user interface.
Includes:
+ disable bell
+ line numbers
+ fonts
+ improved scrolling
+ transparency

#+begin_src emacs-lisp
  ;; disable startup screen
  (setq inhibit-startup-message nil)

  ;; disable ui
  (scroll-bar-mode -1) ; disable visible scrollbar
  (tool-bar-mode -1)   ; disable the toolbar
  (tooltip-mode 1)     ; disable tooltips
  (set-fringe-mode 10) ; give some breathing room
  (menu-bar-mode -1)   ; disable menu bar

#+end_src

** disable bell

#+begin_src emacs-lisp

  ;; disable bell
  (setq ring-bell-function 'ignore) ; TURN OFF ONCE AND FOR ALL?
  ;; (setq ring-bell-function 'silent) ; TURN OFF ONCE AND FOR ALL?

  ;; enable mode line flash bell
  ;; (use-package mode-line-bell
  ;; :if (ring-bell-function 'ignore)
  ;; :config
  ;; (mode-line-bell-mode))


#+end_src

** line numbers

#+begin_src emacs-lisp

  ;; add line numbers
  (global-display-line-numbers-mode t)
  (column-number-mode) ; (columns on modeline)

  ;; line number mode exceptions
  (dolist (mode '(org-mode-hook
                  dired-mode-hook
                  term-mode-hook
                  vterm-mode-hook
                  shell-mode-hook
                  eshell-mode-hook
                  treemacs-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src

** fonts

General fonts for emacs.
(bullets are configured in org-fonts: [[#org-fonts]] )

#+begin_src emacs-lisp

  ;; default font (modeline, minibuffer, default for applications, etc)
  (set-face-attribute 'default nil :font "Fira Code" :height 110)
                                          ;(set-face-attribute 'default nil :font "JetBrains Mono" :height 115)

  ;; fixed pitch font (code blocks, property, startup, etc (can add more))
  (set-face-attribute 'fixed-pitch nil :font "Fira Code" :height 110)

  ;; variable pitch font (toc links, regular text in org, etc...)
  ;; how about Iosveka instead?
  ;; (bullets are configured in org-fonts)
  (set-face-attribute 'variable-pitch nil :font "DejaVu Sans" :height 120 :weight 'regular)

#+end_src

** improved scrolling

#+begin_src emacs-lisp

  (setq mouse-wheel-scroll-amount '(1 ((shift) . 1))) ;; one line at a time
  (setq mouse-wheel-progressive-speed nil) ;; don't accelerate scrolling
  (setq mouse-wheel-follow-mouse 't) ;; scroll window under mouse
  (setq scroll-step 1) ;; keyboard scroll one line at a time
  (setq use-dialog-box nil) ;; (change to nil) make things like yes or no prompts dialogue boxes

#+end_src

** transparency

#+begin_src emacs-lisp

  ;; Set frame transparency and maximize windows by default.
  (set-frame-parameter (selected-frame) 'alpha '(90 . 90))
  (add-to-list 'default-frame-alist '(alpha . (90 . 90)))
  (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  (add-to-list 'default-frame-alist '(fullscreen . maximized))

#+end_src

** shorten y-n prompt

#+begin_src emacs-lisp

  ;; shorten y-n prompt
  (defalias 'yes-or-no-p 'y-or-n-p)

#+end_src

* Basic functionality

basic functionality

** all-the-icons

#+begin_src emacs-lisp

  ;; all-the-icons
  ;; note: on a new machine, must run M-x all-the-icons-install-fonts
  (use-package all-the-icons)

#+end_src

** nerd-fonts

#+begin_src emacs-lisp
  
  ;; nerd-fonts (used by doom-modeline by default)
  ;; note: on a new machine, must run M-x nerd-icons-install-fonts
  (use-package nerd-icons)

#+end_src

** auto-update packages

+ M-x auto-update-package-now to run immediately
+ Updates can break Emacs, so only update when

#+begin_src emacs-lisp

  (use-package auto-package-update
    :custom
    (auto-package-update-interval 7)
    (auto-package-update-prompt-before-update t)
    (auto-package-update-hide-results nil) ; hide pane to see what packages were updated
    :config
    (auto-package-update-maybe)
    (auto-package-update-at-time "15:00"))

#+end_src

** add lisp functions dir to path

#+begin_src emacs-lisp

  (add-to-list 'load-path (concat user-emacs-directory "lisp/"))

#+end_src

* Keybindings

Set keybind related things here.
Includes:
+ global-set-key (<escape> as quit)
+ evil-mode
+ general.el
+ hydra
+ window management
+ buffer management

** make escape quit

Make <escape> quit.

#+begin_src emacs-lisp

  ;; ESC to quit prompts
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
  ;; (global-set-key (kbd "<escape>") #'god-mode-all)
  ;; (global-set-key (kbd "<escape>") #'god-local-mode)

#+end_src

** meow

https://github.com/meow-edit/meow

https://github.com/meow-edit/meow/blob/master/COMMANDS.org

https://user-images.githubusercontent.com/11796018/144637798-f9dfa331-6c2d-4ae0-a11f-936af1a07d5d.png

C-c ? For cheatsheet

things to implement:
+ exit meow insert with a local mode map
+ align the movement keys htns
  + or maybe s --> S and p --> s
+ maybe h up, t left, n down, s right?
  + or stick close to native emacs keybinds...
+ maybe swap m and w so that b and m is back and forth, and w is select?

useful keybinds:
- o - meow-block
- O - meow-next-block

#+begin_src emacs-lisp

  (defun meow-setup ()
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-dvorak)
    (meow-leader-define-key
     '("1" . meow-digit-argument)
     '("2" . meow-digit-argument)
     '("3" . meow-digit-argument)
     '("4" . meow-digit-argument)
     '("5" . meow-digit-argument)
     '("6" . meow-digit-argument)
     '("7" . meow-digit-argument)
     '("8" . meow-digit-argument)
     '("9" . meow-digit-argument)
     '("0" . meow-digit-argument)
     '("/" . meow-keypad-describe-key)
     '("?" . meow-cheatsheet))
    (meow-motion-overwrite-define-key
     ;; custom keybinding for motion state
     ;; '("<escape>" . ignore)
     '("t" . previous-line)
     '("p" . "H-t"))
    (meow-normal-define-key
     '("0" . meow-expand-0)
     '("9" . meow-expand-9)
     '("8" . meow-expand-8)
     '("7" . meow-expand-7)
     '("6" . meow-expand-6)
     '("5" . meow-expand-5)
     '("4" . meow-expand-4)
     '("3" . meow-expand-3)
     '("2" . meow-expand-2)
     '("1" . meow-expand-1)
     '("-" . negative-argument)
     '(";" . meow-reverse)
     '(":" . meow-goto-line) ;; moved from "Q"
     '("," . meow-inner-of-thing)
     '("." . meow-bounds-of-thing)
     '("<" . meow-beginning-of-thing)
     '(">" . meow-end-of-thing)
     '("a" . meow-append)
     '("A" . meow-open-below)
     '("b" . meow-back-word)
     '("B" . meow-back-symbol)
     '("c" . meow-change)
     '("d" . meow-delete)
     '("D" . meow-backward-delete)
     '("e" . meow-line)
     '("E" . meow-goto-line)
     '("f" . meow-find)
     '("F" . meow-search) ;; moved from "s"
     '("g" . meow-cancel-selection)
     '("G" . meow-grab)
     ;; H Directional key moved to the bottom
     '("i" . meow-insert)
     '("I" . meow-open-above)
     '("j" . meow-join)
     '("k" . meow-kill)
     '("l" . meow-till)
     ;; '("m" . meow-mark-word) ;; swap with w, next-word
     ;; '("M" . meow-mark-symbol) ;; swap with w, next-symbol
     '("m" . meow-next-word) ;; moved from "w", mark-word
     '("M" . meow-next-symbol) ;; moved from "W", mark-symbol
     ;; N Directional key moved to the bottom
     '("o" . meow-block)
     '("O" . meow-to-block)
     '("p" . meow-prev)
     '("P" . meow-prev-expand)
     '("q" . meow-quit)
     '("Q" . kill-this-buffer)
     ;; '("Q" . meow-goto-line) ;; move to " : "
     '("r" . meow-replace)
     '("R" . meow-swap-grab)
     ;; '("s" . meow-search) ;; move to F, replace with directional keys
     ;; S Directional key moved to the bottom
     ;; T Directional key moved to the bottom
     '("u" . meow-undo)
     '("U" . meow-undo-in-selection)
     '("v" . meow-visit)
     ;; '("w" . meow-next-word) ;; swap with m, mark-word/symbol
     ;; '("W" . meow-next-symbol)
     '("w" . meow-mark-word) ;; moved from "m", mark-word
     '("W" . meow-mark-symbol) ;; moved from "M", mark-symbol
     '("x" . meow-save)
     '("X" . meow-sync-grab)
     '("y" . meow-yank)
     '("z" . meow-pop-selection)
     '("'" . repeat)
     '("<escape>" . ignore)

     ;; Directional keys:

     ;; is this swap in h and p really better?

     '("h" . meow-left)
     '("H" . meow-left-expand)
     ;; '("h" . meow-prev)
     ;; '("H" . meow-prev-expand)

     '("t" . meow-prev)
     '("T" . meow-prev-expand)
     ;; '("t" . meow-left)
     ;; '("T" . meow-left-expand)

     '("n" . meow-next)
     '("N" . meow-next-expand)

     '("s" . meow-right) ;; Directional, s is ->
     '("S" . meow-right-expand)
     ))

  (use-package meow
    :config
    (meow-setup)
    ;; will "C-g" to meow-insert-exit mess anything up? Consider "C-z" or "C-M-g" instead
    ;; free-keys is very useful!
    (define-key meow-insert-state-keymap (kbd "C-g")  #'meow-insert-exit)
    (define-key meow-insert-state-keymap (kbd "<f5>") #'meow-insert-exit)
    (define-key meow-insert-state-keymap (kbd "<f6>") #'meow-insert-exit) ;; also useful
    (define-key meow-insert-state-keymap (kbd "<f7>") #'meow-insert-exit) ;; fav
    (define-key meow-insert-state-keymap (kbd "<f8>") #'meow-insert-exit) ;; somet easier 2 reach

    (meow-global-mode 1))

#+end_src

** god-mode

https://github.com/emacsorphanage/god-mode

common keybinds:
+ x SPC r y --> C-x r y
+ G q --> C-M-q

is there a way to quit god-mode when hitting C-g?

#+begin_src emacs-lisp

  (use-package god-mode
    :disabled
    :commands god-mode
    :config
    (setq god-exempt-major-modes nil)
    (setq god-exempt-predicates nil)
    (setq god-mode-enable-function-key-translation nil)
    (define-key god-local-mode-map (kbd "i") #'god-local-mode)
    (define-key god-local-mode-map (kbd ".") #'repeat)
    (global-set-key (kbd "C-x C-1") #'delete-other-windows)
    (global-set-key (kbd "C-x C-2") #'split-window-below)
    (global-set-key (kbd "C-x C-3") #'split-window-right)
    (global-set-key (kbd "C-x C-0") #'delete-window)
    (defun my-god-mode-update-cursor-type ()
      (setq cursor-type (if (or god-local-mode buffer-read-only) 'box 'bar)))
    (add-hook 'post-command-hook #'my-god-mode-update-cursor-type)
    ;; (add-to-list 'god-exempt-major-modes 'dired-mode)
    (god-mode))

#+end_src

** evil-mode

#+begin_src emacs-lisp

  ;; evil-mode exclude
  (defun ri/evil-hook ()
    (dolist (mode '(custom-mode
                    eshell-mode
                    git-rebase-mode
                    erc-mode
                    circe-server-mode
                    circe-chat-mode
                    circe-query-mode
                    sauron-mode
                    term-mode))
      (add-to-list 'evil-emacs-state-modes mode)))

  ;; evil-mode
  (use-package evil
    :disabled
    :commands evil-mode
    :init
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump t)
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-undo-system 'undo-fu)
    :config
    (add-hook 'evil-mode-hook 'ri/evil-hook)
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join) ; wowie

    ;; Use visual line motions even outside of visual-line-mode buffers
    ;; -- haven't set up visual line mode yet
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))
  ;;hook
  ;; have these programs be in emacs-mode (C-z)
  ;;(evil-mode-hook . mi/evil-hook)

  ;; evil collections
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))

#+end_src

** evil-undo-system (undo-tree/fu)

https://github.com/apchamberlain/undo-tree.el

#+begin_src emacs-lisp

  ;; To change to undo-tree, update evil-undo-system above.
  ;; undo-tree for evil-undo
  ;; (use-package undo-tree
  ;;   :after evil
  ;;   :init
  ;;   (global-undo-tree-mode 1)
  ;;   :config
  ;;   (setq undo-tree-history-directory-alist
  ;;    '(("." . (concat user-emacs-directory "var/undo-tree-his/")))))

  (use-package undo-fu)

  (use-package undo-fu-session
    :after undo-fu
    :config
    (undo-fu-session-global-mode t))

#+end_src

** general.el

https://github.com/noctuid/general.el

#+begin_src emacs-lisp

  ;; general.el
  (use-package general
    :config
    (general-create-definer ri/leader-keys
      :prefix "C-c"))

#+end_src

** general.el generic binds

Generic toggles

#+begin_src emacs-lisp

  (ri/leader-keys
    "t" '(:ignore t :which-key "toggles"))

#+end_src

Special and Help

#+begin_src emacs-lisp

  (ri/leader-keys
    "s" '(:ignore t :which-key "special"))

#+end_src

Quit emacs / session

#+begin_src emacs-lisp

  (ri/leader-keys
    "q"  '(:ignore t :which-key "quit/session")
    "qq" '(save-buffers-kill-terminal :which-key "quit emacs"))

#+end_src

** hydra

Fast, transient keybinds

#+begin_src emacs-lisp

  ;; hydra (fast, transient keybinds)
  (use-package hydra
    :defer t)

  (defhydra hydra-text-scale (:timeout 5)
    "scale text"
    ("j" text-scale-decrease "out")
    ("k" text-scale-increase "in")
    ("f" nil "finished" :exit t))

  (ri/leader-keys
    "ts" '(hydra-text-scale/body :which-key "scale text"))

#+end_src

** crux

Collection of Ridiculously Useful eXtensions

features:
- auto-align elisp
- C-a moves to the first char on the line instead of the beginning.

#+begin_src emacs-lisp

  ;; maybe replace the first bind with replace kill line with crux?
  (use-package crux
    :bind
    ("C-a" . crux-move-beginning-of-line)
    ("C-k" . crux-smart-kill-line)
    :config
    ;; (global-set-key [remap kill-line] 'crux-smart-kill-line)
    (ri/leader-keys
      "mc" 'crux-cleanup-buffer-or-region))

#+end_src

** expand region

#+begin_src emacs-lisp

  (use-package expand-region
    :commands expand-region)

#+end_src

** avy

jump to any char or line

#+begin_src emacs-lisp

  (use-package avy
    :bind ("C-:" . 'avy-goto-char)
    :commands avy)

#+end_src

** free-keys

#+begin_src emacs-lisp

  (use-package free-keys
    :commands free-keys)

#+end_src

** window management

Ace-window (M-o) documentation

https://github.com/abo-abo/ace-window

#+begin_src emacs-lisp

  (use-package ace-window
    :config
    (setq aw-scope 'frame)
    (setq aw-keys '(?a ?o ?e ?u ?h ?t ?n ?g ?c ?r))
    (defvar aw-dispatch-alist
      '((?d aw-delete-window "Delete Window")
        (?1 delete-other-windows "Delete Other Windows")
        (?s aw-split-window-horz "Split Horz Window")
        (?v aw-split-window-vert "Split Vert Window")
        (?, aw-split-window-fair "Split Fair Window")
        (?o aw-flip-window "Other Window")
        (?w aw-swap-window "Swap Windows")
        (?m aw-move-window "Move Window")
        (?c aw-copy-window "Copy Window")
        (?b aw-switch-buffer-in-window "Select Buffer")
        (?B aw-switch-buffer-other-window "Switch Buffer Other Window")
        (?? aw-show-dispatch-help))
      "List of actions for `aw-dispatch-default'.")
    (global-set-key (kbd "M-o") 'ace-window))

  ;; replace evil-direction w/ package
  (ri/leader-keys
    "w"  '(:ignore t :which-key "window")
    "wv" '(split-window-right :which-key "v-split")
    "ws" '(split-window-below :which-key "h-split")
    "wd" '(delete-window :which-key "close window")
    "wc" '(delete-window :which-key "close window")
    "ww" '(evil-window-next :which-key "next-window")
    "wW" '(evil-window-prev :which-key "prev-window")
    "wh" '(evil-window-left :which-key "window-left")
    "wj" '(evil-window-down :which-key "window-down")
    "wk" '(evil-window-up :which-key "window-up")
    "wl" '(evil-window-right :which-key "window-right")
    "wH" '(evil-window-move-far-left :which-key "move left")
    "wJ" '(evil-window-move-very-bottom :which-key "move down")
    "wK" '(evil-window-move-very-top :which-key "move up")
    "wL" '(evil-window-move-far-right :which-key "move right")
    "wa" '(hydra-window-adjust/body :which-key "window-ratio-adjust")
    "wi" '(:ignore t :which-key "minibuffer")
    "wie" 'minibuffer-keyboard-quit
    "wio" 'switch-to-minibuffer)

  (defhydra hydra-window-adjust (:timeout 5)
    "adjust window split ratio"
    ("h" shrink-window-horizontally "left")
    ("j" enlarge-window "down")
    ("k" shrink-window "up")
    ("l" enlarge-window-horizontally "right")
    ("c" balance-windows "balance")
    ("<enter>" nil "finished" :exit t)
    ("f" nil "finished" :exit t))

#+end_src

** buffer management

#+begin_src emacs-lisp

  (ri/leader-keys
    "k" 'kill-this-buffer
    "b" '(:ignore t :which-key "buffer")
    "bk" 'kill-this-buffer
    "bn" 'next-buffer
    "bp" 'previous-buffer
    "bo" 'meow-last-buffer
    "bb" 'counsel-switch-buffer)

#+end_src

* UI Configuration

Here we have the UI configuration.
Includes:
+ ivy
+ counsel
+ doom-themes
+ doom-modeline
+ rainbow-delimiters
+ which-key
+ helpful
+ help menu

** ivy + counsel

#+begin_src emacs-lisp

  ;; ivy
  (use-package ivy
    :diminish ; hide ivy minor-mode on modeline
    :bind (("C-s" . swiper) ;; fuzzy search tool
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :config
    (message "Ivy got loaded!")
    (ivy-mode 1))

  (use-package ivy-rich
    :after ivy
    :init
    (ivy-rich-mode 1))

  ;; counsel (enhanced standard emacs commands)
  (use-package counsel
    :bind (;("M-x" . counsel-M-x)
                                          ;("C-x b" . counsel-ibuffer)
                                          ;("C-x C-f" . counsel-find-file)
           ("C-M-j" . 'counsel-switch-buffer)
           ("s-c" . 'counsel-switch-buffer)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :custom
    (counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
    :config
    (setq ivy-initial-inputs-alist nil) ;; Don't start searches with ^
    (message "Counsel loaded!")
    (counsel-mode 1))

  ;; adds ivy completion regex and order commands by last used
  (use-package ivy-prescient
    :after counsel
    :custom
    (ivy-prescient-enable-filtering nil)
    :config
    ;; Uncomment the following line to have sorting remembered across sessions!
    (prescient-persist-mode 1)
    (ivy-prescient-mode 1))

#+end_src

** (doom-)themes

#+begin_src emacs-lisp

  ;; doom-themes
  ;; recommended: henna, palenight, snazzy
  (use-package doom-themes
    :bind (("C-h T" . ri/load-theme-and-font-setup))
    :init
    (load-theme 'doom-dracula t))
  ;; (load-theme 'doom-palenight))
  ;; (load-theme 'doom-laserwave t))
  ;;(load-theme 'doom-monokai-spectrum t)
  ;;(load-theme 'doom-snazzy t)

  (use-package ef-themes)

  (use-package catppuccin-theme)

  (defun ri/load-theme-and-font-setup ()
    (interactive)
    (counsel-load-theme)
    (ri/org-font-setup))

  (ri/leader-keys
    "st" '(ri/load-theme-and-font-setup :which-key "choose theme"))

#+end_src

** doom-modeline

#+begin_src emacs-lisp

  ;; doom-modeline
  (use-package doom-modeline
    :init (doom-modeline-mode 1)
    :custom
    ;; (doom-modeline-height 50)
    (doom-dracula-brighter-modeline t)
    (doom-modeline-height 40)
    (doom-modeline-hud nil))

#+end_src

** mini-modeline

#+begin_src emacs-lisp

  (use-package mini-modeline
    ;; :custom
    ;; (mini-modeline-r-format
    ;; :config
    ;; (mini-modeline-mode t)
    )

#+end_src

** rainbow-delimiters

#+begin_src emacs-lisp

  ;; rainbow delimiters
  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))

#+end_src

** modus-themes

#+begin_src emacs-lisp

  ;; (use-package modus-themes
  ;;   :custom
  ;;   ;(modus-themes-mode-line '(borderless))
  ;;   :config
  ;;   (load-theme 'modus-vivendi t))

#+end_src

** which-key

Shows all possible completions for prefixes (C-c, C-x, SPC, etc)

https://github.com/justbur/emacs-which-key

#+begin_src emacs-lisp

  ;; which-key (lists keybinds)
  ;; (add links above source blocks later)
  (use-package which-key
    :defer 0
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 0.3))

#+end_src

** helpful

Shows more info in help menu

useful keybinds:
- C-h b - describe-bindings - search

|-------|
| C-h b |
| C-h R |
|       |

#+begin_src emacs-lisp

  ;; helpful (improves help menu)
  (use-package helpful
    :commands (helpful-callable helpful-variable helpful-command helpful-key)
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind ;; change the function of the command
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key)
    ("C-h M" . which-key-show-major-mode)
    ("C-h H" . helpful-at-point))

  (ri/leader-keys
    "sh" 'helpful-at-point
    "sv" 'describe-variable
    "sf" 'describe-function
    "sk" 'describe-key
    "sM" 'which-key-show-major-mode
    "sm" 'describe-mode
    "sR" 'info-display-manual
    "sP" 'describe-package)

#+end_src

* Org

Configuration for org-mode
Includes:
+ org-fonts
+ bullets, side-padding, tangle, toc, etc.

** Org-fonts

maybe move org-fonts below org-mode, then have a use-package org inside it to run ri/org-font-setup...

#+begin_src emacs-lisp

  (defun ri/org-font-setup ()
    (interactive)
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1)))
      ;; font for bullets
      (set-face-attribute (car face) nil :font "Fira Code" :weight 'regular :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil    :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-table nil    :inherit 'fixed-pitch)
    (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil     :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil    :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil  :inherit 'fixed-pitch)
    (set-face-attribute 'line-number nil :inherit 'fixed-pitch)
    (set-face-attribute 'line-number-current-line nil :inherit 'fixed-pitch))

#+end_src

** Org + agenda

agenda query (custom-agenda-views) documentation: https://orgmode.org/manual/Custom-Agenda-Views.html#Custom-Agenda-Views

org agenda stuff
- when in agenda-commands view, C-n and C-p to move up and down
  - how to move up and down in other views? change size so can see more?

to add tags to a heading,
- counsel-org-tag
  - (M-<enter> to add and continue)

#+begin_src emacs-lisp

  ;; org
  (defun ri/org-mode-setup ()
    (org-indent-mode)
    (variable-pitch-mode 1)
    (visual-line-mode 1))

  (ri/leader-keys
    "o"  '(:ignore t :which-key "org")
    "ox" '(eval-last-sexp :which-key "eval-last-sexp")
    "oX" '(eval-region :which-key "eval-region"))

  (use-package org
    :commands (org-capture org-agenda)
    :hook (org-mode . ri/org-mode-setup)
                                          ;:custom ; do all setq's go in custom?
    :config
    (message "Org Mode loaded!")

    (setq org-ellipsis " ▼")
    (setq org-hide-emphasis-markers t) ; hide formatting chars
    (setq doom-modeline-enable-word-count t)

    ;; org-agenda ----
    (setq org-deadline-warning-days 14)
    (setq org-agenda-start-with-log-mode t) ; enable log-mode by def
    (setq org-log-done 'time)
    (setq org-log-into-drawer t) ; ?

    ;; agenda files ----
    (setq org-agenda-files
          '("~/org/agenda/agenda.org"
            "~/org/agenda/work.org"
            "~/org/agenda/habits.org"))

    ;; todo keywords ----
    (setq org-todo-keywords
          '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
            (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))

    ;; org-refile ----
    ;; (add target locations for org-refile)
    (setq org-refile-targets
          '(("Archive.org" :maxlevel . 1)
            ("work.org" :maxlevel . 1)))
    ;; save org buffers after refiling!
    (advice-add 'org-refile :after 'org-save-all-org-buffers)

    ;; org-habit ----
    (require 'org-habit)
    (add-to-list 'org-modules 'org-habit)
    (setq org-habit-graph-column 60)

    ;; commonly known tasks to appear when counsel-org-tag ----
    ;; org-set-tags-command ?
    (setq org-tag-alist
          '((:startgroup)
                                          ; Put mutually exclusive tags here
            (:endgroup)
            ("@errand" . ?E)
            ("@home" . ?H)
            ("@work" . ?W)
            ("agenda" . ?a)
            ("planning" . ?p)
            ("publish" . ?P)
            ("batch" . ?b)
            ("note" . ?n)
            ("idea" . ?i)))

    ;; Custom Agenda Views! ----
    ;; (easier with org-ql)
    (setq org-agenda-custom-commands
          '(("d" "Dashboard"
             ((agenda "" ((org-deadline-warning-days 7)))
              (todo "NEXT"
                    ((org-agenda-overriding-header "Next Tasks")))
              (tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))

            ("n" "Next Tasks"
             ((todo "NEXT"
                    ((org-agenda-overriding-header "Next Tasks")))))

            ("W" "Work Tasks" tags-todo "+work-email")

            ;; Low-effort next actions
            ("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
             ((org-agenda-overriding-header "Low Effort Tasks")
              (org-agenda-max-todos 20)
              (org-agenda-files org-agenda-files)))

            ("w" "Workflow Status"
             ((todo "WAIT"
                    ((org-agenda-overriding-header "Waiting on External")
                     (org-agenda-files org-agenda-files)))
              (todo "REVIEW"
                    ((org-agenda-overriding-header "In Review")
                     (org-agenda-files org-agenda-files)))
              (todo "PLAN"
                    ((org-agenda-overriding-header "In Planning")
                     (org-agenda-todo-list-sublevels nil)
                     (org-agenda-files org-agenda-files)))
              (todo "BACKLOG"
                    ((org-agenda-overriding-header "Project Backlog")
                     (org-agenda-todo-list-sublevels nil)
                     (org-agenda-files org-agenda-files)))
              (todo "READY"
                    ((org-agenda-overriding-header "Ready for Work")
                     (org-agenda-files org-agenda-files)))
              (todo "ACTIVE"
                    ((org-agenda-overriding-header "Active Projects")
                     (org-agenda-files org-agenda-files)))
              (todo "COMPLETED"
                    ((org-agenda-overriding-header "Completed Projects")
                     (org-agenda-files org-agenda-files)))
              (todo "CANC"
                    ((org-agenda-overriding-header "Cancelled Projects")
                     (org-agenda-files org-agenda-files)))))))

    ;; Org Capture Templates! ----
    ;; (basically quickly add new entries mindlessly)
    (setq org-capture-templates
          `(("t" "Tasks / Projects")
            ("tt" "Task" entry (file+olp "~/org/agenda/agenda.org" "Inbox")
             "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

            ("j" "Journal Entries")
            ("jj" "Journal" entry
             (file+olp+datetree "~/org/agenda/journal.org")
             "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
             ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
             :clock-in :clock-resume
             :empty-lines 1)

            ("jm" "Meeting" entry
             (file+olp+datetree "~/org/agenda/journal.org")
             "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
             :clock-in :clock-resume
             :empty-lines 1)

            ("w" "Workflows")
            ("we" "Checking Email" entry (file+olp+datetree "~/org/agenda/journal.org")
             "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

            ("m" "Metrics Capture")
            ("mw" "Weight" table-line (file+headline "~/org/agenda/metrics.org" "Weight")
             "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)))

    ;; set up org-fonts
    (ri/org-font-setup))

#+end_src

*Keybinds:*

#+begin_src emacs-lisp

  ;; keybinds! -----

  ;; mostly just an example
  (define-key global-map (kbd "C-c j")
    (lambda () (interactive) (org-capture nil "jj")))

  ;; org-agenda leader keybinds (create a separate section?
  (ri/leader-keys
    "oa"  '(:ignore t :which-key "org-agenda")
    "oaa" '(org-agenda :whihc-key "agenda-commands")
    "oas" '(org-agenda-list :which-key "agenda-schedule")
    "oat" '(org-todo-list :which-key "todo-list")
    "oac" '(org-capture :which-key "org-capture")
    "oar" '(org-refile :which-key "org-refile")) ; put refile in org-mode-map?

  (ri/leader-keys
    "md"  '(:ignore t :which-key "date/schedule")
    "mds" 'org-schedule
    "mdd" 'org-deadline
    "mdt" 'org-time-stamp
    "mt" '(org-todo :which-key "todo state set")
    "mq" '(org-set-tags-command :which-key "set tags menu")
    "mQ" '(counsel-org-tag :which-key "set tags list menu")
    "mp" '(org-set-property :which-key "set property")
    "me" '(org-set-effort :which-key "set effort"))
                                          ; C-c org schedule and deadline and time-stamp and org-tags, etc
                                          ; for tag multi-add alt-enter!

#+end_src

** Bullets

#+begin_src emacs-lisp

  (use-package org-bullets
    :hook (org-mode . org-bullets-mode)
    :custom
                                          ;(org-bullets-bullet-list '("⁖" "◉" "○" "✸" "✿")))
    (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))

  ;; replace list hyphen with dot
                                          ;(font-lock-add-keywords 'org-mode
                                          ;                        '(("^ *\\([-]\\) "
                                          ;                           (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

#+end_src

** side-padding

#+begin_src emacs-lisp

  ;; visual-fill-mode (padding)
  (defun ri/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . ri/org-mode-visual-fill)
    :config
    (setq visual-fill-column-enable-sensible-window-split nil))

#+end_src

** Org-babel

code blocks and stuff

*** babel languages

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp . t)
       (python . t)))

    (push '("conf-unix" . conf-unix) org-src-lang-modes))

#+end_src

*** structure templates

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    ;; This is needed as of Org 9.2
    (require 'org-tempo)

    (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
    (add-to-list 'org-structure-template-alist '("py" . "src python"))
    (add-to-list 'org-structure-template-alist '("un" . "src conf-unix")))

#+end_src

*** auto-tangle

#+begin_src emacs-lisp

  ;; org-babel (tangle n stuff)
  ;; Automatically tangle our Emacs.org config file when we save it
  (defun ri/org-babel-tangle-config ()
    (when (string-equal (file-name-directory (buffer-file-name))
                        (expand-file-name user-emacs-directory))
      ;;                                  ^ Formerly user-emacs-directory (now .cache/emacs/)
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'ri/org-babel-tangle-config)))

  (ri/leader-keys
    "ob"  '(:ignore t :which-key "org-babel")
    "obt" '(org-babel-tangle :which-key "tangle")
    "obe" '(org-babel-execute-src-block :which-key "org-babel-execute-src-block"))

#+end_src

** TOC

https://github.com/snosov1/toc-org

#+begin_src emacs-lisp

  (use-package toc-org
    :hook (org-mode . toc-org-mode))

#+end_src

* Development

** lsp-mode

https://emacs-lsp.github.io/lsp-mode/

Cool commands:
+ lsp-find-definition
+ lsp-find-references
  + lsp-ui-peek-find-references
  + lsp-treemacs-references
+ lsp-rename
+ flymake-show-buffer-diagnostics
+ lsp-execute-code-actions
+ lsp-format-buffer
+ lsp-ui-doc-focus-frame
+ lsp-ivy-workspace-symbol
  + lsp-ivy-global-workspace-symbol
+ lsp-treemacs-symbols

#+begin_src emacs-lisp

  ;; breadcrumb automatically enables...
  ;; also "file symbols" is already default args...
  (defun ri/lsp-mode-setup ()
    (setq lsp-headerline-breadcrumb-segments '(path-up-to-project file symbols)))

  (use-package lsp-mode
    :commands (lsp lsp-deferred)
    :hook (lsp-mode . ri/lsp-mode-setup)
    :init
    (setq lsp-keymap-prefix "C-c l")
    :config
    (lsp-enable-which-key-integration t)
    (message "lsp-mode loaded!"))

  ;; change these later...
  ;; prefix is the keys that come before?!?!
  ;; maybe i just don't have the right packages to make lsp-mode-map
                                          ;(ri/ctrl-c-keys
  ;; (general-define-key
  ;;   :keymaps 'lsp-mode-map
  ;;   :prefix lsp-keymap-prefix
  ;;   "l"   '(:ignore t :which-key "lsp")
  ;;   "lg"  '(:ignore t :which-key "find")
  ;;   "lgd" 'lsp-find-definition
  ;;   "lgr" 'lsp-find-references))

  ;; ;; maybe
  ;; ;
                                          ; can't define same keys twice? naw.
  ;; ok what the heck
  ;; (ri/leader-keys
  ;;   :keymaps 'lsp-mode-map
  ;;   "ml"  '(:ignore t :which-key "lsp-find")
  ;;   "mgd" '(lsp-find-definition :wk "definition")
  ;;   "mgr" '(lsp-find-references :wk "references")
  ;;   "mrr" '(lsp-rename :wk "rename all"))

#+end_src

*** lsp-ui

https://emacs-lsp.github.io/lsp-ui/

#+begin_src emacs-lisp

  (use-package lsp-ui
    :hook (lsp-mode . lsp-ui-mode)
    :custom ;; defcustom !!
    (lsp-ui-doc-position 'bottom))

#+end_src

*** lsp-treemacs

#+begin_src emacs-lisp

  (use-package lsp-treemacs
    :after lsp)

#+end_src

*** lsp-ivy

special ivy search functionality for lsp
+ lsp-ivy-workspace-symbol

#+begin_src emacs-lisp

  (use-package lsp-ivy
    :after lsp)

#+end_src

** languages

*** Emacs lisp

#+begin_src emacs-lisp

  (add-hook 'emacs-lisp-mode-hook #'flycheck-mode)

  (ri/leader-keys
    "ml" 'org-lint)

#+end_src

*** Rust

https://robert.kra.hn/posts/rust-emacs-setup/

most rustic features are accessible with C-c C-c
|-------------+-----------|
| C-c C-c C-r | cargo run |
| C-c C-p     | popup     |
|             |           |


#+begin_src emacs-lisp

  ;; rust-analyzer required. gnu guix package?
  (use-package rustic
                                          ;:ensure t ;; no need *
    :hook (rust-mode . lsp-deferred)
    :config
    (setq rustic-format-on-save nil)

    ;; lsp-mode ----
    (lsp-rust-analyzer-cargo-watch-command "check")
    ;; enable / disable the hints as you prefer:
    (lsp-rust-analyzer-server-display-inlay-hints nil)
    (lsp-rust-analyzer-display-lifetime-elision-hints-enable "never") ; skip_trivial
    (lsp-rust-analyzer-display-chaining-hints nil)
    (lsp-rust-analyzer-display-lifetime-elision-hints-use-parameter-names nil) ; def nil
    (lsp-rust-analyzer-display-closure-return-type-hints nil)
    (lsp-rust-analyzer-display-parameter-hints nil) ; def nil
    (lsp-rust-analyzer-display-reborrow-hints "never")

    ;; lsp-ui ----
    (lsp-ui-peek-always-show nil)
    (lsp-ui-sideline-show-hover nil)
    (lsp-ui-doc-enable t))

#+end_src

*** Python

#+begin_src emacs-lisp

  (use-package python-mode
                                          ;:ensure t ;; no need *
    :hook (python-mode . lsp-deferred)
    :custom
    ;; NOTE: Set these if Python 3 is called "python3" on your system!
    ;; (python-shell-interpreter "python3")
    ;; (dap-python-executable "python3")
    (dap-python-debugger 'debugpy)
    :config
    (require 'dap-python))

#+end_src

** Company mode

another completion framework similar to ivy.
code completion in lsp-mode.

#+begin_src emacs-lisp

  (use-package company
    :hook (lsp-mode . company-mode)
    :bind
    ((:map company-active-map
           ("<tab>" . company-complete-selection))
     (:map lsp-mode-map
           ("<tab>" . company-indent-or-complete-common))
     (:map company-search-map
           ("C-t" . company-select-previous-or-abort)))
    :custom
    (company-minimum-prefix-length 1)
    (company-idle-delay 0.0)
    ;; fixes evil-normal and cancel company autocomplete when escape
    ;; doesn't work if escape hit very quickly
    :if (featurep 'evil-mode)
    :config
    (add-hook 'company-mode-hook
              (lambda ()
                (add-hook 'evil-normal-state-entry-hook
                          (lambda ()
                            (company-abort))))))

  (use-package company-box
    :hook (company-mode . company-box-mode))

#+end_src

** Flycheck

#+begin_src emacs-lisp

  (use-package flycheck
    :hook (lsp-mode . flycheck-mode))

#+end_src

** Projectile

project management
bound to C-p
dir-locals are pretty cool
learn more about projectile for better project management

#+begin_src emacs-lisp

  ;; projectile
  ;; (project management)
  ;; (bound to C-p)
  ;; (dir-locals are pretty cool)
  ;; (learn more about projectile for better project management)
  (use-package projectile
    :diminish projectile-mode
    :config
    (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)
    (projectile-mode)
    :custom ((projectile-completion-system 'ivy)) ;; by default auto
    ;; :bind-keymap
    ;; ("C-c p" . projectile-command-map)
    :init
    (when (file-directory-p "~/Code/code")
      (setq projectile-project-search-path '("~/Code/code")))
    (setq projectile-switch-project-action #'projectile-dired))

  ;; counsel-projectile
  ;; (more options in M-o... already installed?)
  ;; (counsel-projectile-rg + M-o for a massive search in project)
  (use-package counsel-projectile
    :after projectile
    :config (counsel-projectile-mode))

#+end_src

** Magit

#+begin_src emacs-lisp

  ;; magit
  ;; (add several links...)
  ;; (magit-status is C-x g)
  ;; (tab to see diff of files)
  ;; (hunks, "?" for all commands, C-c C-k to quit commit, push to remote, ssh?)
  ;; (learn more about magit...)
  (use-package magit
    :commands magit-status
    ;; :bind (:map magit-status-mode-map
    ;;             ("p" . magit-tag)
    ;;             ("t" . magit-section-backward))
    :custom
    ;; what does this do? fullscreen?
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  (ri/leader-keys
    "v"  '(:ignore t :which-key "magit")
    "vv" '(magit-status :which-key "magit")) ; (same as magit)

  ;; forge
  ;; (run forge-pull in a repo to pull down)
  ;; (pull down all issues, pull-reqs, etc)
  ;; (need to create a token first, then put in .authinfo)
  ;; - https://magit.vc/manual/forge/Token-Creation.html#Token-Creation
  ;; - https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started
  (use-package forge
    :after magit)

#+end_src

** auto-indentation

consider parinfer-rust-mode instead?

#+begin_src emacs-lisp

  (use-package aggressive-indent
    :defer t
    :config
    (add-hook 'emacs-lisp-mode-hook #'aggressive-indent-mode))

#+end_src

** commenting

#+begin_src emacs-lisp

  (use-package evil-nerd-commenter
    :custom
    (evil-want-keybinding nil)
    :bind ("M-/" . evilnc-comment-or-uncomment-lines))

#+end_src

* Terminal

** term-mode

term works on basically any device.

next and previous prompts:
+ C-c C-n
+ C-c C-p
+ [ [
+ ] ]

toggle between char and line mode:
+ C-c C-k
+ C-c C-j

if type in char and make evil edits in line mode, does not update.
- consider disabling evil completely while in term, and use zsh's vim?

#+begin_src emacs-lisp

  (use-package term
    :commands term
    :config
    (setq explicit-shell-file-name "zsh")
    (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *"))

#+end_src

*** more colors

makes ranger work.
(depends on ncurses)

#+begin_src emacs-lisp

  (use-package eterm-256color
    :hook (term-mode . eterm-256color-mode))

#+end_src

*** ansi-term

basically the same as term but automatically renames buffers so you can spawn a bunch of them.
also prefix key changed from C-c to C-x.

** vterm

(depends on cmake, libtool-bin, and libvterm (and gcc-toolchain))

maybe try disabling evil in here? actually, it works in bash! but why no zsh?

#+begin_src emacs-lisp

  (use-package vterm
    :commands vterm
    :config
    ;; vv already set vv
    ;;(setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *")
    (setq vterm-shell "bash")
    (setq vterm-max-scrollback 10000))

#+end_src

** shell-mode

in between system shell and emacs...
- kinda broken
- can use evil editing
- counsel-shell-history

- M-p
- M-n

- not good, but works great on windows...

** shell-pop (pop-up)

Hit s-<return> to bring up scratchpad terminal.

https://github.com/kyagi/shell-pop-el

#+begin_src emacs-lisp

  (use-package shell-pop
    :commands shell-pop
    :custom
    (shell-pop-universal-key nil)
    (shell-pop-default-directory "/home/mio")
    (shell-pop-shell-type (quote ("vterm" "*vterm*" (lambda nil (vterm shell-pop-term-shell)))))
    (shell-pop-term-shell "/bin/zsh")
    (shell-pop-window-size 40)
    (shell-pop-window-position "bottom"))

#+end_src

** eat

Emulate a terminal in Eshell!
(non-gnu?)

#+begin_src emacs-lisp

#+end_src

** Eshell

fix neofetch
+ C-r

#+begin_src emacs-lisp

  ;; eshell config
  (defun ri/configure-eshell ()
    ;; Save command history when commands are entered.
    ;;   Commands usually don't save until close, so if crashes, loses all progress.
    (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

    ;; Truncate buffer for performance
    (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

    ;; Bind some useful keys for evil-mode
    (evil-define-key '(normal insert visual) eshell-mode-map (kbd "C-r") 'counsel-esh-history)
    ;; fixes the issue with cursor going to the beginning... fixed?
    (evil-define-key '(normal insert visual) eshell-mode-map (kbd "<home>") 'eshell-bol)
    (evil-normalize-keymaps)

    (setq eshell-history-size         10000
          eshell-buffer-maximum-lines 10000
          eshell-hist-ignoredups t
          eshell-scroll-to-bottom-on-input t))

  ;; themes
  (use-package eshell-git-prompt
    :after eshell)

  (use-package eshell
    :hook (eshell-first-time-mode . ri/configure-eshell)
    :config
    (with-eval-after-load 'esh-opt
      (setq eshell-destroy-buffer-when-process-dies t)
      (setq eshell-visual-commands '("htop" "zsh" "vim" "ssh")))

    (eshell-git-prompt-use-theme 'powerline))

  (ri/leader-keys
    "ot" '(vterm :which-key "vterm")
    "oe" '(eshell :which-key "eshell"))

#+end_src

* Files

file management, etc

#+begin_src emacs-lisp

  (ri/leader-keys
    "f"  '(:ignore t :which-key "files")
    "fr" '(counsel-recentf :which-key "recent files")
    "ff" '(find-file :which-key "find-file")
    "fp" '(lambda () (interactive)
            (find-file (expand-file-name "~/.dotfiles/.emacs.d/"))
            :which-key "open Emacs.org"))

#+end_src

** Dired

- Keybinds:
  |-----+------------+---+---------+----------------------+---+------+---------------------|
  |     | Marking    |   |         | Open/view/quit       |   |      | Copying/deleting/   |
  |     |            |   |         |                      |   |      | compressing         |
  |-----+------------+---+---------+----------------------+---+------+---------------------|
  | J   | search     |   | <ret>   | open file            |   | C    | copy file           |
  | m   | mark       |   | g o     | view file            |   | R    | rename/Move         |
  | %   | mark regex |   | S-<ret> | open in split window |   | % R  | rename regex        |
  | \*  | mark type  |   | M-<ret> | view file (scan)     |   | d/x  | delete selection    |
  | t   | inverts    |   | (    \) | hide info            |   | D    | delete/Trash file   |
  | u/U | unmark     |   | g r     | refresh dired        |   | Z    | compress/uncompress |
  | k/K | kill       |   | C-M-J   | ivy-immediate-done   |   | c    | compress advanced   |
  |     |            |   | H       | show/hide dots       |   |      | create empty file   |
  |     |            |   |         |                      |   |      |                     |
  |-----+------------+---+---------+----------------------+---+------+---------------------|
  |     |            |   |         |                      |   |      |                     |
  |-----+------------+---+---------+----------------------+---+------+---------------------|
  |     | Others     |   |         | Misc                 |   |      | Regex               |
  |-----+------------+---+---------+----------------------+---+------+---------------------|
  | T   | timestamp  |   | C-x C-q | Read only mode (ZZ)  |   | \&   | previous expression |
  | M   | -rw-r--r-- |   | &       | run program on file  |   | \1   |                     |
  | O   | owner      |   | I       | appends dired buffer |   | %s// |                     |
  | G   | group      |   |         |                      |   |      |                     |
  | S   | symlink    |   |         |                      |   |      |                     |
  | L   | load lisp  |   |         |                      |   |      |                     |
  |     |            |   |         |                      |   |      |                     |
  |-----+------------+---+---------+----------------------+---+------+---------------------|


#+begin_src emacs-lisp

  ;; dired
  (use-package dired
    :ensure nil ; make sure use-package doesn't try to install it.
    :commands (dired dired-jump) ; defer loading of this config until a command is executed.
    :custom
    (dired-listing-switches "-agho --group-directories-first")
    (dired-dwim-target t) ; auto select dir to move to if another dired window open.
    (delete-by-moving-to-trash t)
    ;;(dired-compress-files-alist) ; add more file types to compression.
    :if (featurep 'evil-mode)
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "h" 'dired-single-up-directory
      "l" 'dired-single-buffer
      "f" 'dired-create-empty-file))
  ;;     ^ Might not work if using two dired windows! (dired-up-directory, dired-find-file)

  ;; HAS TO COME AFTER dired because using ":after dired"
  ;; Reuses the current Dired buffer to visit a directory without
  ;; creating a new buffer.
  (use-package dired-single
    :after dired)

  (defun ri/all-the-icons-dired-helper ()
    (interactive)
    (if (equal dirvish-override-dired-mode nil)
        (all-the-icons-dired-mode)))

  (use-package all-the-icons-dired
    :hook (dired-mode . ri/all-the-icons-dired-helper))

  (use-package dired-open
    :commands (dired dired-jump)
    :config
    (setq dired-open-extensions
          '(("mkv" . "mpv")
            ("png" . "feh"))))

  ;; ----custom-function-----------

  ;; >>> Consider replacing dired hide dotfiles with dired-x dired omit files?

  ;; if enabled, when my-dired-mode-hook is run, re-enable dired-hide-dotfiles-mode
  (defvar ri/dired-hide-dotfiles-mode--persist 1)

  (defun ri/dired-hide-dotfiles-mode--toggle ()
    ;; when run, toggles dired-hide-dotfiles-mode and assistant var
    (interactive)
    (if dired-hide-dotfiles-mode
        (dired-hide-dotfiles-mode 0)
      (dired-hide-dotfiles-mode 1))
    (setq ri/dired-hide-dotfiles-mode--persist dired-hide-dotfiles-mode))

  ;; ------------------------------

  (use-package dired-hide-dotfiles
    ;; :commands (dired dired-jump)
    :config
    ;; Does this even work?!?!?!?!?!?
    (define-key dired-mode-map (kbd "z") 'ri/dired-hide-dotfiles-mode--toggle)
    :if (featurep 'evil-mode)
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "H" 'ri/dired-hide-dotfiles-mode--toggle))

  (defun my-dired-mode-hook ()
    (if ri/dired-hide-dotfiles-mode--persist
        (dired-hide-dotfiles-mode)))
                                          ;
  (add-hook 'dired-mode-hook #'my-dired-mode-hook)

#+end_src

*Leader keys:*

#+begin_src emacs-lisp

  (ri/leader-keys
    "d"  '(:ignore t :which-key "dired")
    "dd" 'dired
    "dj" 'dired-jump
    "dh" 'ri/dired-hide-dotfiles-mode--toggle)

#+end_src

** dirvish

https://github.com/alexluigit/dirvish

+ Consider dired-x dired-omit-files instead?

#+begin_src emacs-lisp

  (use-package dirvish
    :init (dirvish-override-dired-mode)
    :commands (dired dired-jump)
    :custom
    (dirvish-quick-access-entries ; It's a custom option, `setq' won't work
     '(("h" "~/"                            "Home")
       ("o" "~/org/"                        "Org")
       ("d" "~/Downloads/"                  "Downloads")
       ("e" "/home/mio/.dotfiles/.emacs.d/" "Emacs user directory")
       ("p" "~/Pictures/"                   "Pictures")
       ("c" "~/Code/"                       "Code")
       ("m" "/mnt/"                         "Drives")
       ("t" "~/.local/share/Trash/files/"   "Trash")))
    :config
    ;; (define-key dirvish-mode-map (kbd "z") 'ri/dired-hide-dotfiles-mode--toggle)
    (setq dired-listing-switches
          ;; "-ahgo --group-directories-first"
          "-l --almost-all --human-readable --group-directories-first --no-group") ; AhoG
    (setq dired-dwim-target t) ; auto select dir to move to if another dired window open.
    (setq delete-by-moving-to-trash t)
    (setq dirvish-attributes
          '(all-the-icons file-time file-size collapse subtree-state vc-state git-msg))
    :bind
    (:map dirvish-mode-map
          ("h" . dired-up-directory)
          ("r" . dired-sort-toggle-or-edit)
          ("s" . dired-open-file)
          ;; ("z" . 'ri/dired-hide-dotfiles-mode--toggle)
          ))

  ;;  (("C-c f" . dirvish-fd)
  ;; :map dirvish-mode-map ; Dirvish inherits `dired-mode-map'
  ;; ("a"   . dirvish-quick-access)
  ;; ("f"   . dirvish-file-info-menu)
  ;; ("y"   . dirvish-yank-menu)
  ;; ("N"   . dirvish-narrow)
  ;; ("^"   . dirvish-history-last)
  ;; ("h"   . dirvish-history-jump) ; remapped `describe-mode'
  ;; ("s"   . dirvish-quicksort)    ; remapped `dired-sort-toggle-or-edit'
  ;; ("v"   . dirvish-vc-menu)      ; remapped `dired-view-file'
  ;; ("TAB" . dirvish-subtree-toggle)
  ;; ("M-f" . dirvish-history-go-forward)
  ;; ("M-b" . dirvish-history-go-backward)
  ;; ("M-l" . dirvish-ls-switches-menu)
  ;; ("M-m" . dirvish-mark-menu)
  ;; ("M-t" . dirvish-layout-toggle)
  ;; ("M-s" . dirvish-setup-menu)
  ;; ("M-e" . dirvish-emerge-menu)
  ;; ("M-j" . dirvish-fd-jump)))

    #+end_src

** sudo-edit

#+begin_src emacs-lisp

  ;; doesn't work... what is tramp?
  (use-package sudo-edit
    :custom
    (sudo-edit-local-method "doas")
    :config
    (global-set-key (kbd "C-c C-r") 'sudo-edit))

#+end_src

* Programs

** elfeed

an rss feed reader for emacs

#+begin_src emacs-lisp

  ;; rss
  ;; maybe don't need, phone is enough?
  ;; maybe syncthing and import from database?
  ;; dont use commands elfeed, scan at startup?
  (use-package elfeed
    :commands elfeed)

#+end_src

** eww

Consider emacs-w3m, where it's faster and better!

#+begin_src emacs-lisp

  ;; eww is shite, also SPC and h trigger prefix. w3 browser?
  (setq browse-url-browser-function 'eww-browse-url)

  (use-package eww
    :bind (:map eww-mode-map
                ("n" . next-line) ;; orig next-url
                ("]" . eww-next-url)
                ("[" . eww-previous-url)
                ("T" . eww-top-url)
                ("t" . nil)
                ("H-t" . previous-line))) ;; (physically "p")

#+end_src

** gnus

Usenet newsgroup reader

https://www.maketecheasier.com/emacs-usenet-reader-with-gnus/

#+begin_src emacs-lisp

  (use-package gnus
    :commands gnus
    :config
    (setq user-full-name '"aili")
    (setq user-mail-address '"yourname@email.invalid")
    (setq gnus-select-method '(nnnil))
    (setq gnus-secondary-select-methods '((nntp "news.gmane.io")
                                          ;(nntp "news.alt.religion.emacs")
                                          ;(nntp "gnu.emacs.sex")
                                         ))

    (setq gnus-directory (concat user-emacs-directory "News/")
          gnus-startup-file (concat user-emacs-directory "News/.newsrc")
          message-directory (concat user-emacs-directory "Mail/")))

    ;;(setq gnus-secondary-select-methods '((nntp "alt.religion.emacs")))

#+end_src

** ement

a matrix client for emacs
https://github.com/alphapapa/ement.el

#+begin_src emacs-lisp

  ;; matrix client
  (use-package ement
    :commands ement)

#+end_src

** emacs-jabber

An XMPP client for Emacs.
https://codeberg.org/emacs-jabber/emacs-jabber/

#+begin_src emacs-lisp

  (use-package jabber
     :commands jabber)

#+end_src

** erc

an irc client for emacs
https://github.com/alphapapa/ement.el

#+begin_src emacs-lisp

  ;; erc
  ;; make erc start after startup?
  (use-package erc
    :commands erc)

#+end_src

** mastodon.el

A mastodon/fediverse client for Emacs.
https://codeberg.org/martianh/mastodon.el

#+begin_src emacs-lisp

  (use-package mastodon
    :commands mastodon)

#+end_src

* Applications

unix applications go here
+ firejail

** Xmodmap

#+begin_src conf-unix :tangle ../.Xmodmap

  clear lock
  keycode 66 = Control_L Escape

#+end_src

** mpv

#+begin_src conf-unix :tangle ../.config/mpv/mpv.conf

  #

#+end_src

** zshrc

#+begin_src conf-unix :tangle ../.zshrc

  #
  ## config for .zshrc
  #

  # Enable colors and change prompt:
  autoload -U colors && colors
  PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "

  # History in cache directory:
  HISTFILE=~/.cache/zsh/history		# note: do "mkdir -p ~/.cache/zsh/" first!
  HISTSIZE=100000
  SAVEHIST=100000

  # Basic auto/tab complete:
  autoload -U compinit
  zstyle ':completion:*' menu select
  zmodload zsh/complist
  compinit
  _comp_options+=(globdots)		# Include hidden files.

  #--------------------------------------------------------------

  # vi mode
  bindkey -e # emacs, not -v (vim)
  # export KEYTIMEOUT=1

  # # Change cursor shape for different vi modes.
  # function zle-keymap-select () {
  #     case $KEYMAP in
  #         vicmd) echo -ne '\e[1 q';;      # block
  #         viins|main) echo -ne '\e[5 q';; # beam
  #     esac
  # }
  # zle-line-init() {
  #     zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
  #     echo -ne "\e[5 q"
  # }

  # zle -N zle-keymap-select
  # zle -N zle-line-init
  # echo -ne '\e[5 q' # Use beam shape cursor on startup. ]
  # preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.}


  #--------------------------------------------------------------

  #
  ## End of main
  #

  # Export
  export HISTORY_IGNORE="(ls|cd|pwd|exit|doas reboot|history|cd -| cd ..)"
  #export EDITOR="emacsclient -t -a ''"
  #export VISUAL="emacsclient -c -a emacs"
  #export VISUAL="emacsclient -t -a ''"
  export VISUAL="emacsclient"
  export EDITOR="$VISUAL"
  #export MANPAGER="sh -c 'col -bx | bat -l man -p'"


  # Import aliases
  [ -f "$HOME/.aliasrc" ] && source "$HOME/.aliasrc"

  # syntax highlighting plugin (https://github.com/zsh-users/zsh-syntax-highlighting)
  source /usr/share/zsh/site-functions/zsh-syntax-highlighting.zsh

  # Disable bell
  unsetopt BEEP


  # vterm integration

  vterm_printf() {
      if [ -n "$TMUX" ] && ([ "${TERM%%-*}" = "tmux" ] || [ "${TERM%%-*}" = "screen" ]); then
          # Tell tmux to pass the escape sequences through
          printf "\ePtmux;\e\e]%s\007\e\\" "$1"
      elif [ "${TERM%%-*}" = "screen" ]; then
          # GNU screen (screen, screen-256color, screen-256color-bce)
          printf "\eP\e]%s\007\e\\" "$1"
      else
          printf "\e]%s\e\\" "$1"
      fi
  }


#+end_src

** Firejail

*** disable-common.local

#+begin_src conf-unix :tangle ../.config/firejail/disable-common.local

  blacklist ${HOME}/Documents/secure
  blacklist ${HOME}/School/school/Important-docs

#+end_src

*** keepassxc.local

#+begin_src conf-unix :tangle ../.config/firejail/keepassxc.local

  ## Browser Integration
  # So can access database and keyfile
  noblacklist ${HOME}/Documents/secure
  # Allow browser profile, required for browser integration (i think)
  noblacklist ${HOME}/.librewolf
  # On github wiki for needed
  noblacklist ${RUNUSER}/app
  #
  ##

  ## ETC
  #
  #dbus-user.talk org.freedesktop.secrets
  #
  dbus-user.talk org.freedesktop.Notifications
  #
  ##

#+end_src

*** librewolf.local

#+begin_src conf-unix :tangle ../.config/firejail/librewolf.local

  #whitelist ${RUNUSER}/run/user/$UID/librewolf

  ## KeepassXC browser integration
  noblacklist ${RUNUSER}/app
  whitelist ${RUNUSER}/kpxc_server
  whitelist ${RUNUSER}/org.keepassxc.KeePassXC.BrowserServer
  #
  noblacklist ${HOME}/.mozilla
  whitelist ${HOME}/.mozilla
  #
  noblacklist ${HOME}/Documents/secure
  #

  ## ETC
  #
  # native notifications
  dbus-user.talk org.freedesktop.Notifications
  #
  # inhibiting screensavers
  dbus-user.talk org.freedesktop.ScreenSaver

#+end_src

*** steam.local

#+begin_src conf-unix :tangle ../.config/firejail/steam.local

  #ignore seccomp

  # private-bin is disabled while in testing, but is known to work with multiple games.
  # Add the next line to your steam.local to enable private-bin.
  #private-bin awk,basename,bash,bsdtar,bzip2,cat,chmod,cksum,cmp,comm,compress,cp,curl,cut,date,dbus-launch,dbus-send,desktop-file-edit,desktop-file-install,desktop-file-validate,dirname,echo,env,expr,file,find,getopt,grep,gtar,gzip,head,hostname,id,lbzip2,ldconfig,ldd,ln,ls,lsb_release,lsof,lspci,lz4,lzip,lzma,lzop,md5sum,mkdir,mktemp,mv,netstat,ps,pulseaudio,python*,readlink,realpath,rm,sed,sh,sha1sum,sha256sum,sha512sum,sleep,sort,steam,steamdeps,steam-native,steam-runtime,sum,tail,tar,tclsh,test,touch,tr,umask,uname,update-desktop-database,wc,wget,wget2,which,whoami,xterm,xz,zenity

  # To view screenshots add the next line to your steam.local.
  #private-bin eog,eom,gthumb,pix,viewnior,xviewer

#+end_src

* Special

Not sure if this works or not lol

#+begin_src emacs-lisp

  ;; Keep customization settings in a temporary file (does this even work?)
  (setq custom-file
        (if (boundp 'server-socket-dir)
            (expand-file-name "custom.el" server-socket-dir)
          (expand-file-name (format "emacs-custom-%s.el" (user-uid)) temporary-file-directory)))
  (load custom-file t)

#+end_src

* DVORAK swap x and u

#+begin_src emacs-lisp

  ;; org binding on M-t so make all t key bindings translate to p ?

  ;; also god mode

  ;(global-set-key (kbd "C-h") 'backward-kill-word)
  (global-set-key (kbd "C-t") 'previous-line)

  (global-set-key (kbd "C-u") ctl-x-map)
  ;; (global-set-key (kbd "C-z") 'universal-argument)
  ;; (global-set-key (kbd "C-M-u") 'universal-argument)
  (global-set-key (kbd "C-M-g") 'universal-argument)

#+end_src

* Runtime performance

#+begin_src emacs-lisp

  ;; make gc pauses faster by decreaseing the threshold.
  (setq gc-cons-threshold (* 2 1000 1000))

#+end_src
